CONFIG_NET_L2_ETHERNET=y

# The Address Resolution Protocol (ARP) is a communication protocol for discovering the link layer address,
# such as a MAC address, associated with an internet layer address, typically an IPv4 address.
# It is part of L3.
CONFIG_NET_ARP=y
CONFIG_NET_ARP_TABLE_SIZE=2
CONFIG_NET_ARP_GRATUITOUS=y

CONFIG_ETH_DRIVER=y
CONFIG_ETH_PHY_DRIVER=y
CONFIG_ETH_INIT_PRIORITY=80
CONFIG_PHY_INIT_PRIORITY=70
CONFIG_PHY_AUTONEG_TIMEOUT_MS=4000
CONFIG_PHY_MONITOR_PERIOD=500